### ISSUE TITLE
Valid plans failed by version 0.12.24

### ISSUE THREAD

**Issue by bartlettt** [ljfranklin/terraform-resource#115] opened 2020-04-24 12:52 UTC
I've encountered a new behaviour where valid terraform plans are marked as failed by the latest 0.12.24 images.

I can't find a way to get the specific digests that are broken. I extend your image automatically so I can provide timestamps. My extended image adds some binaries, so I don't think that is causing the issue.

The tag 0.12.24 published at Apr 14 2020 13:46:00 UTC+1 behaves **correctly**
The tag 0.12.24 published at Apr 22 2020 19:18:06 UTC+1 behaves **incorrectly**

Incorrect behaviour:
**Without changes**
```
No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.
▲ ▲ ▲ ▲ ▲ ▲ ▲ ▲ ▲ ▲ Terraform Plan ▲ ▲ ▲ ▲ ▲ ▲ ▲ ▲ ▲ ▲
Failed To Run Terraform Plan!
2020/04/23 22:12:19 Plan Error: Failed to run Terraform command: exit status 1
```

**With changes**
```
Plan: 1 to add, 0 to change, 1 to destroy.
▲ ▲ ▲ ▲ ▲ ▲ ▲ ▲ ▲ ▲ Terraform Plan ▲ ▲ ▲ ▲ ▲ ▲ ▲ ▲ ▲ ▲
Failed To Run Terraform Plan!
2020/04/24 12:28:32 Plan Error: Failed to run Terraform command: exit status 1
```

As an extra ask, would it be possible for you to add additional tags to your images, e.g. `0.12.24-v1`, that way I have more granular control over what image I use. I attempted to use digests, but it seems that can't be specified for a resource_type in concourse.

My team and I are finding this resource incredibly useful! Thanks for the good work.
Tom

**Comment by ljfranklin** [comment] 2020-04-24 13:20
A recent [PR](https://github.com/ljfranklin/terraform-resource/pull/114) is a likely culprit. I just reverted this change in the `0.12.24` and `latest` images, can you retry and confirm that the issue is gone? I'll investigate why this change failed later today, potentially it doesn't handle the no-op plan case.

> would it be possible for you to add additional tags to your images

This has come up once or twice and I think it'll cause more problems than it solves. Often the resource requires changes to deal with breaking changes in new Terraform versions. Communicating to users that their issue was actually fixed in 0.12.24-v3 seems like worse UX overall. Downside is that bugs do sometimes sneak thru which isn't great either. I'll keep giving this some thought though.

**Comment by ljfranklin** [comment] 2020-04-24 13:24
@bartlettt if you needed to add a workaround in the future, you can tag your own image temporarily:

```
docker tag ljfranklin/terraform-resource@sha256:b441be7bfa0be45ea1eadaeb6c911fc326c7eefa7eb524afba7f8fc4eca7dddf yourname/terraform-resource:0.12.24-plan-fix
```

**Comment by bartlettt** [comment] 2020-04-24 14:26
I can confirm the issue is resolved; thanks for the rapid response!

In terms of tagging, I had imagined the `0.12.24` tag would always point at your latest version. Additional tags would be created so you can opt into an older version of a tag.

**Round 1**
| sha | tags |
| ----- | ------ |
| xxx | 0.12.24, 0.12.24-v1 |

**Round 2**
| sha | tags |
| ----- | ------ |
| xxx | 0.12.24-v1 |
| yyy | 0.12.24, 0.12.24-v2 |

**Round 3**
| sha | tags |
| ----- | ------ |
| xxx | 0.12.24-v1 |
| yyy | 0.12.24-v2 |
| zzz | 0.12.24, 0.12.24-v3 |

**Comment by bartlettt** [comment] 2020-04-24 14:30
You could also tag with the git commit sha: `0.12.24-sha_xxxxxxxxxx`

My team tags every image we build with its git sha, as well as a semantic version

**Comment by odise** [comment] 2020-04-25 08:33
@bartlettt Could you maybe share your configuration? That would make things easier for me. Thanks in advance.

**Comment by ljfranklin** [comment] 2020-04-25 20:13
> I had imagined the 0.12.24 tag would always point at your latest version...You could also tag with the git commit sha: 0.12.24-sha_xxxxxxxxxx

Oh, I misunderstood the original suggestion. I like it! [Done](https://github.com/ljfranklin/terraform-resource/commit/02b265287d480f5e2471864ed9ebb241f7bdaf6c), you should start seeing these tags on the next trip through CI.

After taking a look, I'm also a bit stumped on the plan failure. @bartlettt could you do us a favor and try re-running your plan with the `ljfranklin/terraform-resource:0.12.24-plan-log` image? That image writes some additional logs to `/tmp/tf-plan.log` inside the container that were previously getting swallowed. After your job fails you can run `fly i -j your-pipeline/your-job 'cat /tmp/tf-plan.log'` or similar to see the logs. Hopefully there's a useful error in there, although be careful with sharing the contents as there are definitely credentials in the plan output.

**Comment by bartlettt** [comment] 2020-04-26 10:14
@odise This is an example of my put step:
```
      - put: docker-image
        params:
          build: git-source
          build_args_file: generated/build_args.json
          additional_tags: git-source/VERSION
          tag_file: git-source/.git/ref
          tag_prefix: git_
          tag_as_latest: true
          cache: true
          cache_tag: latest
        get_params:
          skip_download: true
```

The following tags would be created:
```
1.0.0
git_xxxxxxxxxxx
latest
```

**Comment by bartlettt** [comment] 2020-04-26 10:30
@ljfranklin This is my build log:

```
bash-5.0# cat ./tf-plan.log

Warning: Value for undeclared variable

The root module does not declare a variable named "output_key" but a value was
found in file
"/tmp/terraform-resource-out567142779/421360286vars-file.tfvars.json". To use
this value, add a "variable" block to the configuration.

Using a variables file to set an undeclared variable is deprecated and will
become an error in a future release. If you wish to provide certain "global"
settings to all configurations in your organization, use TF_VAR_...
environment variables to set these instead.


Error: rpc error: code = ResourceExhausted desc = grpc: received message larger than max (4525545 vs. 4194304)
```

I use the following providers:
```
provider.aws
provider.helm
provider.kubernetes
provider.vault
provider.null
provider.local
provider.random
provider.template
provider.tls
```

I suspect that this may be a kubernetes/helm related issue. Those providers tends to throw cryptic grpc errors when they hit a problem.

**Comment by ljfranklin** [comment] 2020-04-27 12:56
@bartlettt looks like the plan file may have been too big to upload to your backend. I added some gzip compression to the JSON plan field, can you give `ljfranklin/terraform-resource:0.12.24-plan-log` another shot when you get a chance to see if that resolves the error?

**Comment by bartlettt** [comment] 2020-04-28 11:42
I've tested that image, and the plans succeed now. The changeless log is:

```
bash-5.0# cat ./tf-plan.log
stateful_string.plan_output: Creating...
stateful_string.plan_output_json: Creating...
stateful_string.plan_output: Creation complete after 0s [id=184e29fc-8251-485e-8816-f9bad7ec29eb]
stateful_string.plan_output_json: Creation complete after 0s [id=390cff84-3ec3-4ae7-a33b-ff79f1e2d86e]

Warning: Value for undeclared variable

The root module does not declare a variable named "output_key" but a value was
found in file
"/tmp/terraform-resource-out139035900/770609195vars-file.tfvars.json". To use
this value, add a "variable" block to the configuration.

Using a variables file to set an undeclared variable is deprecated and will
become an error in a future release. If you wish to provide certain "global"
settings to all configurations in your organization, use TF_VAR_...
environment variables to set these instead.


Apply complete! Resources: 2 added, 0 changed, 0 destroyed.

Outputs:

plan_content = <sensitive>
plan_content_json = <sensitive>
```

**Comment by ljfranklin** [comment] 2020-04-28 11:57
@bartlettt great, thanks for the verification! I re-pushed the JSON plan feature with the compression added.

**Closed by ljfranklin** 2020-04-28 11:57 UTC
