### ISSUE TITLE
Intermittent "invalid character '/' after top-level value" error

### ISSUE THREAD

**Issue by divyabhargov** [ljfranklin/terraform-resource#44] opened 2017-10-20 00:06 UTC
We hit "invalid character '/' after top-level value" sometimes. Its a flakiness and happens approximately once in 20 runs. A retrigger without any changes makes the problem go away. Have you encountered this or do you have any suggestion for us how we can debug this further ?

**Comment by ljfranklin** [comment] 2017-10-20 00:33
@divyabhargov I have never seen that error. Is this during a `put` to the terraform resource? Could you attach a screenshot?

**Comment by divyabhargov** [comment] 2017-11-06 23:11
Here are some screenshots when the error occurs:
![screen1](https://user-images.githubusercontent.com/1180082/32468749-665aeb34-c304-11e7-98dc-4637f9ed695f.png)
![screen2](https://user-images.githubusercontent.com/1180082/32468750-6685dd08-c304-11e7-89b8-687e283cba70.png)

**Comment by ljfranklin** [comment] 2017-11-07 16:59
@divyabhargov this is a weird one, still looking into it. Started a convo with the Concourse team here: https://concourseci.slack.com/archives/C07RY25QF/p1510072021000782. Seems like something is printing to Stdout that shouldn't be but I can't find where that would be happening.

Couple questions:
- Are you using `ljfranklin/terraform-resource:latest` or some other image?
- Are you using an S3-compatible storage with a custom endpoint or AWS S3?
- Any other things that are unique about your Terraform templates or terraform-resource config?

**Comment by Seraf** [comment] 2017-11-07 21:08
Hello, we already had a random fail with this error also :)

We are using the latest terraform resource, with a S3 endpoint. First time we had this problem, and weren't able to reproduce it.

**Comment by ljfranklin** [comment] 2017-11-08 01:19
Good grief, I just looked through all my old builds and this has happened to me 2 times out of 100+ builds. I'll try to add some debug logging to a custom image and run it in a loop or something.

**Comment by ljfranklin** [comment] 2017-11-08 17:04
Still struggling to reproduce this. Latest finding is that the "invalid character '/' after top-level value" is reproducible in isolation if you try to unmarshal a `log` time stamp as JSON, e.g. `log.Println` will print `2017/11/08 16:39:08 ...`. Concourse tries to unmarshal everything written to Stdout as a JSON response which is where the error is getting raised. So somewhere in the code there's a `log` statement that is going to Stdout. But I can't find it, maybe it is buried in some dependency.

**Comment by ljfranklin** [comment] 2017-11-09 01:33
This was fun. I copied stdout to stderr in a test image and ran the job in a loop all day. On run number 422 I finally got the log message: `2017/11/08 21:48:35 Request body type has been overwritten. May cause race conditions`. Looks like this was an issue fixed on the aws SDK: https://github.com/aws/aws-sdk-go/issues/868. I'll push a fix in a bit to bump the AWS SDK and nil out its logger.

**Closed** 2017-11-09 01:43 UTC

**Comment by divyabhargov** [comment] 2017-11-09 18:51
Thank you so much. This is exciting

**Comment by doty-pivotal** [comment] 2017-11-09 18:51
Thanks for taking a look at this, and tracking it all the way down.

**Comment by hubertgrzeskowiak** [comment] 2019-03-01 15:50
I just had this error and it showed up every time I ran a plan at random points of the plan. It complained about a seemingly random character (sometimes alphanumerics, sometimes slashes).

I found out I had a custom module instantiation with a parameter the module didn't define. After fixing this error, I did not get any more of these cryptic Terraform errors.
